### ISSUE TITLE
Please remove TortoiseSVN Alert

### ISSUE THREAD

**Issue by AnWeber** [fantacytyx/vscode-tortoise-svn#1]
I automatically sync all my extensions in vscode between my enviroments. In my private enviroment I don't need tortoisesvn and it is not installed. On start of vscode this alert is shown:

Current setting "TortoiseSVN.tortoiseSVNProcExePath" is invalid.Please specify a correct one, then restar VSCode.

How can I disable this message in this enviroment?

Thanks.

**Comment by TangYanxin** [comment]
Please delete **TortoiseSVN** in your private enviroment

**Comment by AnWeber** [comment]
After every automated sync?

**Comment by TangYanxin** [comment]
I released  the new version.
- when user don't set `TortoiseSVN.tortoiseSVNProcExePath`, get the `TortoiseProc.exe` path from registry 
- postpone check `TortoiseProc.exe` path until command execution
