### ISSUE TITLE
VSCode SCM Provider

### ISSUE THREAD

**Issue by seanmcbreen** [fantacytyx/vscode-tortoise-svn#2]
This is an FYI message - fell free to close....

Hello,

Thanks for creating and extension for VS Code, we have now added an API for VSCode to enable pluggable SCM Providers.  This is currently in the 'preview' state and only in the 'insiders' build.  Our plan is to move this into 'stable' in our next release (early April 17).   

This lays the foundation for rich SCM Extensions to be distributed through the marketplace.  These extensions will have access to all of the features our Git support leverages (this itself is now only using the public API).  

**Our ASK** If you are interested in helping create an SCM provider, we want to help you and have created a new repo with all of the required details including - timelines, instructions, sample implementations, ...   https://github.com/Microsoft/vscode-SCMBuilders

Head on over there if you want to help to get going or to monitor progress - with any luck in the coming months we should have a set of high quality SCM providers for VS Code.

Sean
VS Code Team Member

**Comment by TangYanxin** [comment]
Let me have a try!

**Comment by seanmcbreen** [comment]
Very cool - we also now have 3 reference implementations:
1. [Perforce](https://marketplace.visualstudio.com/items?itemName=slevesque.perforce)
2. [TFVC](https://github.com/Microsoft/vsts-vscode/tree/master/src/tfvc), and
3. [Git](https://github.com/Microsoft/vscode/tree/master/extensions/git)
